---
galaxy_info:
  role_name: olt_port_restart
  author: Votre équipe réseau
  description: Vérifie et redémarre automatiquement les ports OLT selon des critères
  company: Votre entreprise
  
  license: MIT
  
  min_ansible_version: "2.9"
  
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
  
  galaxy_tags:
    - networking
    - olt
    - automation
    - pon

dependencies: []